states:
  {
    _WIP: "ğŸ— Work in progress",
    main: "ğŸŒ Main page",
    transaction: "ğŸ’¸ Transaction",
    task_current: "ğŸ—’ Task",
    finances: "ğŸ’¸ Finances",
    tasks: "ğŸ—’ Tasks",
    reminders: "â° Reminders",
    utilities: "ğŸš° Utilities",
    clothes: "ğŸ‘š Clothes",
    storage: "ğŸ“¦ Storage",
    health: "ğŸ¥ Health",
    food: "ğŸ¥˜ Food",
    plants: "ğŸª´ Plants",
    people: "ğŸ‘« People",
    transactions: "ğŸ‘› Transactions",
    income: "ğŸ‘› Income",
    expenses: "ğŸ‘› Expenses",
    transfers: "ğŸ‘› Transfers",
    financial_accounts: "ğŸ¦ Financial accounts",
    payment_cards: "ğŸ’³ Payment cards",
    organizations: "ğŸ¬ Organizations",
    categories: "ğŸ· Categories",
    currencies: "ğŸ’± Currencies",
    pills: "ğŸ’Š Pills",
    diseases: "ğŸ¤§ğŸ¦  Diseases",
    body_temperature: "ğŸ¤’ Temperature",
    tasks_current: "ğŸ—’ Current tasks",
    tasks_scheduled: "â° Scheduled tasks",
    _BACK: "â¬…ï¸ Back",
    _RECORDS: "ğŸ—„ See all",
    _ADD: "ğŸ†• Add",
    _NEXT: "â¡ï¸ Next",
    _CANCEL: "âŒ Cancel",
    _SUBMIT: "âœ… Submit",
  }
