states:
  {
    _WIP: "ğŸ— Work in progress",
    main: "ğŸŒ Main page",
    transaction: "ğŸ’¸ Transaction",
    task_current: "ğŸ—’ Task",
    finances: "ğŸ’¸ Finances",
    tasks: "ğŸ—’ Tasks",
    reminders: "â° Reminders",
    utilities: "ğŸš° Utilities",
    clothes: "ğŸ‘š Clothes",
    storage: "ğŸ“¦ Storage",
    health: "ğŸ¥ Health",
    food: "ğŸ¥˜ Food",
    plants: "ğŸª´ Plants",
    people: "ğŸ‘« People",
    people_RECORDS: "List of users",
    people_VIEW: "User",
    people_PARAM_name: "User name",
    people_PARAM_SHORT_name: "Name",
    people_PARAM_emoji: "User emoji",
    people_PARAM_SHORT_emoji: "Emoji",
    transactions: "ğŸ‘› Transactions",
    income: "ğŸ‘› Income",
    income_RECORDS: "List of income",
    income_VIEW: "Income",
    income_PARAM_date: "Income date",
    income_PARAM_SHORT_date: "Date",
    income_PARAM_currency: "Income currency",
    income_PARAM_SHORT_currency: "Currency",
    income_PARAM_sum: "Income sum",
    income_PARAM_SHORT_sum: "Sum",
    income_PARAM_financial_account: "Income account",
    income_PARAM_SHORT_financial_account: "account",
    income_PARAM_payment_card: "Income card",
    income_PARAM_SHORT_payment_card: "Card",
    income_PARAM_organization: "Income organization",
    income_PARAM_SHORT_organization: "Organization",
    income_PARAM_description: "Income description",
    income_PARAM_SHORT_description: "Description",
    expenses: "ğŸ‘› Expenses",
    expenses_RECORDS: "List of expenses",
    expenses_VIEW: "Expense",
    expenses_PARAM_date: "Expense date",
    expenses_PARAM_SHORT_date: "Date",
    expenses_PARAM_currency: "Expense currency",
    expenses_PARAM_SHORT_currency: "Currency",
    expenses_PARAM_sum: "Expense sum",
    expenses_PARAM_SHORT_sum: "Sum",
    expenses_PARAM_financial_account: "Expense account",
    expenses_PARAM_SHORT_financial_account: "Account",
    expenses_PARAM_payment_card: "Expense card",
    expenses_PARAM_SHORT_payment_card: "Card",
    expenses_PARAM_organization: "Expense organization",
    expenses_PARAM_SHORT_organization: "Organization",
    expenses_PARAM_description: "Expense description",
    expenses_PARAM_SHORT_description: "Description",
    transfers: "ğŸ‘› Transfers",
    transfers_RECORDS: "List of transfers",
    transfers_VIEW: "Transfer",
    transfers_PARAM_date: "Transfer date",
    transfers_PARAM_SHORT_date: "Date",
    transfers_PARAM_currency_source: "Transfer source currency",
    transfers_PARAM_SHORT_currency_source: "Source currency",
    transfers_PARAM_sum_source: "Transfer source sum",
    transfers_PARAM_SHORT_sum_source: "Source sum",
    transfers_PARAM_account_source: "Transfer source account",
    transfers_PARAM_SHORT_account_source: "Source account",
    transfers_PARAM_currency_target: "Transfer target currency",
    transfers_PARAM_SHORT_currency_target: "Target currency",
    transfers_PARAM_sum_target: "Transfer target sum",
    transfers_PARAM_SHORT_sum_target: "Target sum",
    transfers_PARAM_account_target: "Transfer target account",
    transfers_PARAM_SHORT_account_target: "Target account",
    transfers_PARAM_comission: "Transfer comission",
    transfers_PARAM_SHORT_comission: "Comission",
    transfers_PARAM_description: "Transfer description",
    transfers_PARAM_SHORT_description: "Description",
    financial_accounts: "ğŸ¦ Financial accounts",
    financial_accounts_RECORDS: "List of financial accounts",
    financial_accounts_VIEW: "Financial account",
    financial_accounts_PARAM_name: "Account name",
    financial_accounts_PARAM_SHORT_name: "Name",
    financial_accounts_PARAM_number: "Account number",
    financial_accounts_PARAM_SHORT_number: "Number",
    financial_accounts_PARAM_operator: "Account operator",
    financial_accounts_PARAM_SHORT_operator: "Operator",
    financial_accounts_PARAM_type: "Account type",
    financial_accounts_PARAM_SHORT_type: "Type",
    financial_accounts_PARAM_currency: "Account currency",
    financial_accounts_PARAM_SHORT_currency: "Currency",
    financial_accounts_PARAM_credit: "Is account credit?",
    financial_accounts_PARAM_SHORT_credit: "Is credit?",
    financial_accounts_PARAM_owner: "Account owner",
    financial_accounts_PARAM_SHORT_owner: "Owner",
    financial_accounts_SELECT_type_BANK: "Bank Account",
    financial_accounts_SELECT_type_SIM: "SIM Account",
    payment_cards: "ğŸ’³ Payment cards",
    payment_cards_RECORDS: "List of payment cards",
    payment_cards_VIEW: "Payment card",
    payment_cards_PARAM_number: "Card number",
    payment_cards_PARAM_SHORT_number: "Number",
    payment_cards_PARAM_financial_account: "Card account",
    payment_cards_PARAM_SHORT_financial_account: "Account",
    payment_cards_PARAM_payment_system: "Card payment system",
    payment_cards_PARAM_SHORT_payment_system: "Payment system",
    organizations: "ğŸ¬ Organizations",
    organizations_RECORDS: "List of organizations",
    organizations_VIEW: "Organization",
    organizations_PARAM_name: "Organization name",
    organizations_PARAM_SHORT_name: "Name",
    organizations_PARAM_keywords: "Organization keywords",
    organizations_PARAM_SHORT_keywords: "Keywords",
    organizations_PARAM_category: "Organization category",
    organizations_PARAM_SHORT_category: "Category",
    organizations_PARAM_emoji: "Organization emoji",
    organizations_PARAM_SHORT_emoji: "Emoji",
    categories: "ğŸ· Categories",
    currencies: "ğŸ’± Currencies",
    currencies_RECORDS: "List of currencies",
    currencies_VIEW: "Currency",
    currencies_PARAM_name: "Currency name",
    currencies_PARAM_SHORT_name: "Name",
    currencies_PARAM_code: "Currency code (ISO 4217)",
    currencies_PARAM_SHORT_code: "Code (ISO 4217)",
    currencies_PARAM_emoji: "Currency emoji",
    currencies_PARAM_SHORT_emoji: "Emoji",
    pills: "ğŸ’Š Pills",
    diseases: "ğŸ¤§ğŸ¦  Diseases",
    body_temperature: "ğŸ¤’ Temperature",
    tasks_current: "ğŸ—’ Current tasks",
    tasks_scheduled: "â° Scheduled tasks",
    _BACK: "â¬…ï¸ Back",
    _RECORDS: "ğŸ—„ See all",
    _ADD: "ğŸ†• Add",
    _NEXT: "â¡ï¸ Next",
    _SKIP: "ğŸ¦¥ Skip",
    _CANCEL: "âŒ Cancel",
    _SUBMIT: "âœ… Submit",
  }
